node {
    
    stage('Clean') {
        sh 'rm *.zip || true'
        sh 'rm *.tar || true'
    }

    stage('Clone repository') {
        // Let's make sure we have the repository cloned to our workspace
        checkout scm
    }

    stage('Embed App Embedded Defender') {
        withCredentials([usernamePassword(credentialsId: 'twistlock_creds', passwordVariable: 'TL_PASS', usernameVariable: 'TL_USER')]) {
            sh 'curl -k -u $TL_USER:$TL_PASS --output ./twistcli https://$TL_CONSOLE/api/v1/util/twistcli'
            sh 'sudo chmod a+x ./twistcli'        
            sh './twistcli app-embedded embed --console-host $TL_CONSOLE -address https://$TL_CONSOLE -u $TL_USER -p $TL_PASS --data-folder /twistlock/ --output-file app-embedded-defender.zip --app-id app-embedded-dockerfile Dockerfile'
        } 
    }

    stage('Build Image') {
        unzip dir: 'app-embedded-defender/', glob: '', zipFile: 'app-embedded-defender.zip'
        sh "mv run.sh app-embedded-defender/run.sh"
        app = docker.build("app-embedded-defender:${env.BUILD_ID}", "./app-embedded-defender/")
        sh "docker save app-embedded-defender:${env.BUILD_ID} > app-embedded-defender-${env.BUILD_ID}.tar"
    }

    stage('Publish Container') {
        sshagent (credentials: ['bb4af5c8-29c5-4063-b318-0e62f75700ca']) {
            sh "ssh -o StrictHostKeyChecking=no davila_paloaltonetworks_com@temp-demobuild.davila.demo.twistlock.com docker stop app-embedded-docker | true"
            sh "ssh -o StrictHostKeyChecking=no davila_paloaltonetworks_com@temp-demobuild.davila.demo.twistlock.com docker rm app-embedded-docker | true"
            sh "ssh -o StrictHostKeyChecking=no davila_paloaltonetworks_com@temp-demobuild.davila.demo.twistlock.com docker load < ./app-embedded-defender-${env.BUILD_ID}.tar"
            sh "ssh -o StrictHostKeyChecking=no davila_paloaltonetworks_com@temp-demobuild.davila.demo.twistlock.com docker run --name app-embedded-docker -d -p 8080:80 app-embedded-defender:${env.BUILD_ID}"
            sh "ssh -o StrictHostKeyChecking=no davila_paloaltonetworks_com@temp-demobuild.davila.demo.twistlock.com docker logs app-embedded-docker"
        }
    }
}
