AWSTemplateFormatVersion: "2010-09-09"
Resources:
  taskdefinition:
    Properties:
      ContainerDefinitions:
      - Cpu: 256
        DependsOn:
        - Condition: HEALTHY
          ContainerName: TwistlockDefender
        EntryPoint:
        - /var/lib/twistlock/fargate/defender
        - fargate
        - entrypoint
        - sh
        - -c
        Environment:
        - Name: TW_IMAGE_NAME
          Value: kimkarimm/foundation-vouchers-test:v1
        - Name: TW_CONTAINER_NAME
          Value: my-app
        - Name: DEFENDER_TYPE
          Value: fargate
        - Name: FARGATE_TASK
          Value: fargate-task-definition
        - Name: FILESYSTEM_MONITORING
          Value: "true"
        - Name: FIPS_ENABLED
          Value: "false"
        Essential: true
        Image: kimkarimm/foundation-vouchers-test:v1
        LinuxParameters:
          Capabilities:
            Add:
            - SYS_PTRACE
        MemoryReservation: 512
        Name: my-app
        PortMappings:
        - ContainerPort: 80
          HostPort: 80
          Protocol: tcp
        VolumesFrom:
        - ReadOnly: false
          SourceContainer: TwistlockDefender
      - EntryPoint:
        - /usr/local/bin/defender
        - fargate
        - sidecar
        Environment:
        - Name: INSTALL_BUNDLE
          Value: eyJzZWNyZXRzIjp7InNlcnZpY2UtcGFyYW1ldGVyIjoiVU5LdXpCQk9hejBGQ0hnWW5oV25zYmlYQVNmVnZlK0FzTWNScTB0MDVhbWtjYmxOTGdLT0JuTzNXWnd6RHVBOW10cGpWNVErbVBJMGZJSHl0Nnh4TGc9PSJ9LCJnbG9iYWxQcm94eU9wdCI6eyJodHRwUHJveHkiOiIiLCJub1Byb3h5IjoiIiwiY2EiOiIiLCJ1c2VyIjoiIiwicGFzc3dvcmQiOnsiZW5jcnlwdGVkIjoiIn19LCJjdXN0b21lcklEIjoidXMtNC0xNjEwNTYzMDciLCJhcGlLZXkiOiJtSFh5ZlFDMVJtbE00dVhjK2FSbVVMU1cxREdITVpobzZFKzhybGZ5K2YwOXJoSC8rR3ZEQmJjamhWSHlSWlFpaTlQelV2cWxmRGN2K2xVYUhJenluUT09IiwibWljcm9zZWdDb21wYXRpYmxlIjpmYWxzZX0=
        - Name: DEFENDER_TYPE
          Value: fargate
        - Name: FARGATE_TASK
          Value: fargate-task-definition
        - Name: WS_ADDRESS
          Value: wss://us-west1.cloud.twistlock.com:443
        - Name: FILESYSTEM_MONITORING
          Value: "true"
        - Name: FIPS_ENABLED
          Value: "false"
        Essential: true
        HealthCheck:
          command:
          - /usr/local/bin/defender
          - fargate
          - healthcheck
          interval: 5
          retries: 3
          startPeriod: 1
          timeout: 5
        Image: registry-auth.twistlock.com/tw_pfv4mzkgtidy8xfpudrnoq9w0wykrjmh/twistlock/defender:defender_30_03_122
        Name: TwistlockDefender
        PortMappings: []
      Cpu: 256
      ExecutionRoleArn: arn:aws:iam::108863513136:role/ecsTaskExecutionRole
      Family: fargate-task-definition
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
      - EC2
      - FARGATE
    Type: AWS::ECS::TaskDefinition
