pipeline {
    agent any
    
    environment {
        PRISMA_API_URL="${pc_tenant}"
    }
    
    stages {

        stage('PrismaCloud Scanning') {
            steps {
                    script {
                        docker.image('bridgecrew/checkov:latest').inside("--entrypoint=''") {
                          try {
                            sh '''
                                checkov --version
                                checkov -d . -o cli -o junitxml --output-file-path console,results.xml --bc-api-key ${pc_user}::${pc_password} --compact --quiet --soft-fail
                            '''
                          } catch (err) {
                              throw err
                        }
                    }
                }
            }
        }
    }
}