AWSTemplateFormatVersion: 2010-09-09
Description: Template para habilitaci?n rate limit WAF/Shield advanced
Parameters: 
  ShieldBucketName: 
    Type: String
  ShieldBucketNameDev:
    Type: String
  LimitCount:
    Type: String
  ProjectName:
    Type: String
  AppCode:
    Type: String
  EnvType:
      Description: Environment Type.
      Type: String
      AllowedValues:
        - prod
        - qa
        - dev
      ConstraintDescription: Must specify prod, qa or dev depending on the environment that you're working.
Conditions:
  CreateProdStream: !Equals
    - !Ref EnvType
    - prod
  CreateDevQAStream: !Not
    - !Equals
      - !Ref EnvType
      - prod
Resources:
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: EC2TargetGroup
      LoadBalancerArn:
          Ref: ApplicationLoadBalancing
      Port: 80
      Protocol: HTTP
  ApplicationLoadBalancing:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: alb-imperva-demo
      Scheme: internet-facing
      Subnets:
        - subnet-09dee58dcfaf9924c
        - subnet-06b4f7908e3375b5c
      Type: application
  ShieldWebACLELB: 
    Type: 'AWS::WAFv2::WebACL'
    Properties:
      Name: !Ref 'AWS::StackName'
      Scope: REGIONAL
      Description: ACL para Rate Limit Shield en balanceadores
      DefaultAction:
        Block: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: ShieldWebACLMetricLB
      Rules:
        - Priority: 0
          Name: RateBasedRuleCount
          Action:
            Count: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateBasedRuleCount
          Statement:
            RateBasedStatement:
              AggregateKeyType: FORWARDED_IP
              ForwardedIPConfig:
                HeaderName: x-forwarded-for
                FallbackBehavior: MATCH
              Limit: !Ref LimitCount
        - Name: CountImperva
          Priority: 1
          Action:
            Allow: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CountImperva
          Statement: 
            IPSetReferenceStatement:
              Arn: !GetAtt 
                - IpSet
                - Arn 
        - Name: CountHealthcheck
          Priority: 2
          Action:
            Allow: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CountHealthcheck
          Statement: 
            IPSetReferenceStatement:
              Arn: !GetAtt 
                - IpSetHealthcheck
                - Arn
  WebACLLoadBalancerAssociation: #Este recurso nos ayuda a realizar la asociacion del balanceador previamente creado con la ACL: ShieldWebACLELB
    Type: 'AWS::WAFv2::WebACLAssociation'
    Properties:
      WebACLArn: !GetAtt 
          - ShieldWebACLELB #Nombre de la ACL para el balanceadorrr
          - Arn     
      ResourceArn: !Ref ApplicationLoadBalancing  
         
